#!/bin/bash
#PBS -N dieback_region
#PBS -q copyq
#PBS -l mem=4GB
#PBS -l jobfs=1GB
#PBS -l ncpus=1
#PBS -P xe2
#PBS -l walltime=00:15:00
#PBS -l storage=gdata/xe2+gdata/ub8

# Notes:
# 'copyq' queue required for internet access
# 'ub8' storage access required for OzWald

# Print out input variables to the error log
echo "Starting"
###


# activate virtual environment:
source /g/data/xe2/John/geospatenv/bin/activate
module load gdal/3.6.4
# module load netcdf/4.7.3

# Change working directory
wd=/home/147/cb8590/Projects/PaddockTS
cd $wd

python DAESIM_preprocess/tests_local.py
# python DAESIM_preprocess/silo_daily.py --variable evap_morton_lake --lat '-34.3890427' --lon 148.469499 --buffer 0.1 --start_year 2020 --end_year 2020 --outdir outdir --stub TEST --tmpdir /g/data/xe2/datasets/Climate_SILO --plot
