# +
#  Pysheds documentation is here: https://mattbartos.com/pysheds/
import os

# Dependencies
import numpy as np
from pysheds.grid import Grid
import rasterio

# +
dirmap = (64, 128, 1, 2, 4, 8, 16, 32)

def pysheds_accumulation(tiff_file):
    """Read in the grid and dem and calculate the water flow direction and accumulation"""
    
    # Load both the dem (basically a numpy array), and the grid (all the metadata like the extent)
    grid = Grid.from_raster(tiff_file)
    dem = grid.read_raster(tiff_file)

    # Hydrologically enforce the DEM so water can flow downhill to the edge and not get stuck
    pit_filled_dem = grid.fill_pits(dem)
    flooded_dem = grid.fill_depressions(pit_filled_dem)
    inflated_dem = grid.resolve_flats(flooded_dem)

    # Calculate the aspect (fdir) and accumulation of water (acc)
    fdir = grid.flowdir(inflated_dem)
    acc = grid.accumulation(fdir)

    return grid, dem, fdir, acc

def calculate_slope(tiff_file):
    """Calculate the slope of a DEM"""
    with rasterio.open(tiff_file) as src:
        dem = src.read(1)  
        transform = src.transform 
    gradient_y, gradient_x = np.gradient(dem, transform[4], transform[0])
    slope = np.arctan(np.sqrt(gradient_x**2 + gradient_y**2)) * (180 / np.pi)
    return slope

def calculate_TWI(tiff_file):
    """Calculate the topographic wetness index based on upstream area and local slope"""
    _, _, _, acc = pysheds_accumulation(tiff_file)
    slope = calculate_slope(filepath)
    slope_radians = np.radians(slope)
    slope_radians[slope_radians == 0] = np.finfo(float).eps     # Avoid division by 0
    twi = np.log((acc + 1) / np.tan(slope_radians))
    return twi


# -

# %%time
if __name__ == '__main__':
    if os.path.expanduser("~").startswith("/home/"):
        paddockTS_dir = os.path.join(os.path.expanduser("~"), "Projects/PaddockTS")
    else:
        paddockTS_dir = os.path.dirname(os.getcwd())
    os.chdir(paddockTS_dir)

    # This assumes a tif file has already been generated by running terrain_tiles.py
    filepath = "./Test_terrain.tif"
    
    grid, dem, fdir, acc = pysheds_accumulation(filepath)
    slope = calculate_slope(filepath)
    twi = calculate_TWI(filepath)
    print(dem.shape)
